name: Linting Action

on:
  pull_request:
    branches: [main, dev]
  workflow_dispatch:

jobs:
  formatting:
    runs-on: ubuntu-latest
    name: Linting
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Running Linting
        uses: ./
